name: Docs

on:
  push:
    branches:
      - master
    tags:
      - '*.*.*'

jobs:
  docker-push:
    name: Build API documentation
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:

      - name: Checkout
        uses: actions/checkout@v4

      - name: Install dependencies
        run: make install

      - name: Generate docs
        run: make generate-docs

      - name: Push
        uses: s0/git-publish-subdir-action@v2.6.0
        env:
          REPO: self
          BRANCH: docs
          FOLDER: docs
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SKIP_EMPTY_COMMITS: true
