name: Release

on:
  push:
    tags:
      - '*.*.*'

jobs:
  release:
    name: Create release
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:

      - name: Checkout
        uses: actions/checkout@v4

      - name: Get version
        id: version
        run: |
          echo "contents<<VERSIONEOF" >> $GITHUB_OUTPUT
          echo "$GITHUB_REF" | cut -d / -f 3 >> $GITHUB_OUTPUT
          echo "VERSIONEOF" >> $GITHUB_OUTPUT

      - name: Changelog
        id: changelog
        run: |
          echo "contents<<CHANGELOGEOF" >> $GITHUB_OUTPUT
          sed -e "1,/## ${{ steps.version.outputs.contents }}/d" -e '/##/,$d' CHANGELOG.md >> $GITHUB_OUTPUT
          echo "CHANGELOGEOF" >> $GITHUB_OUTPUT

      - name: Create release
        id: create_release
        uses: shogo82148/actions-create-release@v1
        with:
          body: ${{ steps.changelog.outputs.contents }}
